/**
 * @sam-ai/educational
 *
 * Advanced educational engines for SAM AI Tutor
 * - Exam generation with Bloom's Taxonomy alignment
 * - AI-powered answer evaluation
 * - Cognitive progress tracking
 * - Spaced repetition scheduling
 *
 * @packageDocumentation
 */

// ============================================================================
// ENGINE EXPORTS
// ============================================================================

export {
  // Exam Engine
  AdvancedExamEngine,
  createExamEngine,

  // Evaluation Engine
  SAMEvaluationEngine,
  EvaluationEngine,
  createEvaluationEngine,

  // Blooms Analysis Engine
  BloomsAnalysisEngine,
  createBloomsAnalysisEngine,

  // Personalization Engine
  PersonalizationEngine,
  createPersonalizationEngine,

  // Content Generation Engine
  ContentGenerationEngine,
  createContentGenerationEngine,

  // Resource Engine
  ResourceEngine,
  createResourceEngine,

  // Multimedia Engine
  MultimediaEngine,
  createMultimediaEngine,

  // Financial Engine
  FinancialEngine,
  createFinancialEngine,

  // Predictive Engine
  PredictiveEngine,
  createPredictiveEngine,

  // Analytics Engine
  AnalyticsEngine,
  createAnalyticsEngine,

  // Memory Engine
  MemoryEngine,
  createMemoryEngine,

  // Research Engine
  ResearchEngine,
  createResearchEngine,

  // Trends Engine
  TrendsEngine,
  createTrendsEngine,

  // Achievement Engine
  AchievementEngine,
  createAchievementEngine,

  // Integrity Engine
  IntegrityEngine,
  createIntegrityEngine,

  // Course Guide Engine
  CourseGuideEngine,
  createCourseGuideEngine,

  // Enhanced Depth Analysis Engine
  EnhancedDepthAnalysisEngine,
  createEnhancedDepthAnalysisEngine,
  enhancedDepthEngine,

  // Collaboration Engine
  CollaborationEngine,
  createCollaborationEngine,

  // Social Engine
  SocialEngine,
  createSocialEngine,

  // Innovation Engine
  InnovationEngine,
  createInnovationEngine,

  // Market Engine
  MarketEngine,
  createMarketEngine,

  // Unified Bloom's Engine (Priority 1: Unified Bloom's Engine)
  UnifiedBloomsEngine,
  createUnifiedBloomsEngine,
  UnifiedBloomsAdapterEngine,
  createUnifiedBloomsAdapterEngine,

  // Phase 2 Engines - Practice Problems, Adaptive Content, Socratic Teaching
  PracticeProblemsEngine,
  createPracticeProblemsEngine,
  AdaptiveContentEngine,
  createAdaptiveContentEngine,
  SocraticTeachingEngine,
  createSocraticTeachingEngine,

  // Knowledge Graph Engine (New)
  KnowledgeGraphEngine,
  createKnowledgeGraphEngine,

  // Microlearning Engine (New)
  MicrolearningEngine,
  createMicrolearningEngine,

  // Metacognition Engine (New)
  MetacognitionEngine,
  createMetacognitionEngine,

  // Competency Engine (New)
  CompetencyEngine,
  createCompetencyEngine,

  // Peer Learning Engine (New)
  PeerLearningEngine,
  createPeerLearningEngine,
} from './engines';

// ============================================================================
// TYPE EXPORTS
// ============================================================================

export type {
  // Common Types
  QuestionType,
  QuestionDifficulty,
  EvaluationType,

  // Exam Engine Types
  ExamEngineConfig,
  ExamGenerationConfig,
  ExamGenerationDefaults,
  ExamGenerationResponse,
  EnhancedQuestion,
  QuestionOption,
  QuestionMetadata,
  ExamMetadata,
  BloomsComparison,
  AdaptiveSettings,
  AdaptiveRule,
  PerformanceThreshold,
  StudentProfile,
  Skill,
  Resource,

  // Evaluation Engine Types
  EvaluationEngineConfig,
  EvaluationSettings,
  EvaluationContext,
  EvaluationRubric,
  RubricCriterion,
  RubricLevel,
  EvaluationResult,
  SubjectiveEvaluationResult,
  PartialCreditItem,
  GradingAssistance,
  RubricScore,
  ComparisonAnalysis,
  ObjectiveAnswer,

  // Blooms Analysis Engine Types
  BloomsAnalysisConfig,
  BloomsDistribution,
  BloomsAnalysisResult,
  BloomsRecommendation,
  CognitiveProfile,
  CognitiveProgressUpdate,
  BloomsLevelUpdate,
  LearningRecommendation,
  SpacedRepetitionInput,
  SpacedRepetitionResult,

  // Course Analysis Types
  CourseAnalysisInput,
  ChapterInput,
  SectionInput,
  QuestionInput,
  ExamInput,
  CourseAnalysisOptions,
  CourseBloomsAnalysisResult,
  ChapterBloomsAnalysis,
  SectionBloomsAnalysis,
  ActivityAnalysis,
  LearningPathway,
  CognitivePath,
  CognitiveStage,
  LearningGap,
  CourseRecommendations,
  ContentRecommendation,
  AssessmentRecommendation,
  ActivitySuggestion,
  StudentImpact,
  SkillDeveloped,
  GrowthProjection,
  CareerPath,

  // Question Bank Types
  QuestionBankEntry,
  QuestionBankQuery,
  QuestionBankStats,

  // Assessment Generation Types
  AssessmentGenerationConfig,
  GeneratedAssessment,
  AssessmentMetadata,
  ScoringGuide,
  AssessmentRubric,
  AdaptiveQuestionRequest,
  StudentResponse,
  AdaptiveQuestionSettings,
  AdaptiveQuestionResult,
  PerformanceAnalysis,

  // Engine Interfaces
  ExamEngine,
  EvaluationEngine as IEvaluationEngine,
  BloomsAnalysisEngine as IBloomsAnalysisEngine,

  // Personalization Engine Types
  PersonalizationEngineConfig,
  LearningStyle,
  LearningBehavior,
  SessionPattern,
  ContentInteraction,
  AssessmentRecord,
  TimePreference,
  DeviceUsage,
  LearningStyleProfile,
  OptimizedContent,
  ContentAdaptation,
  EmotionalState,
  EmotionIndicator,
  MotivationProfile,
  MotivationFactor,
  PersonalizedPath,
  LearningNode,
  LearningEdge,
  AlternativePath,
  PersonalizationContext,
  PersonalizationResult,
  PersonalizationInsight,
  StudentProfileInput,
  LearningHistory,
  Interaction,
  StudentInfo,

  // Content Generation Engine Types
  ContentGenerationEngineConfig,
  GenerationDefaults,
  GenerationStyle,
  GenerationDepth,
  GenerationConfig,
  LearningObjectiveInput,
  CourseContentOutput,
  CourseOutlineOutput,
  ChapterOutlineOutput,
  SectionOutlineOutput,
  TopicInput,
  AssessmentOutput,
  AssessmentType,
  GeneratedQuestion,
  ConceptInput,
  ExerciseOutput,
  ExerciseType,
  TestCaseOutput,
  CourseForStudyGuide,
  StudyGuideOutput,
  KeyTopicOutput,
  SummaryOutput,
  ResourceOutput,
  ContentInput,
  LanguageInput,
  LocalizedContentOutput,
  GlossaryTermOutput,
  ContentGenerationEngine as IContentGenerationEngine,

  // Resource Engine Types
  ResourceEngineConfig,
  TopicForResource,
  ExternalResource,
  ResourceType,
  LicenseType,
  ResourceCost,
  QualityScore,
  QualityFactor,
  LicenseStatus,
  ROIAnalysis,
  AlternativeResource,
  ResourceRecommendation,
  StudentResourceProfile,
  ResourceDiscoveryConfig,
  ResourceEngine as IResourceEngine,

  // Multimedia Engine Types
  MultimediaEngineConfig,
  VideoContent,
  AudioContent,
  InteractiveContent,
  InteractiveElement,
  VideoAnalysis,
  AudioAnalysis,
  InteractiveAnalysis,
  MultiModalAnalysis,
  MultiModalContentTypes,
  AccessibilityReport,
  VisualElement,
  KeyMoment,
  AccessibilityCompliance,
  AccessibilityIssue,
  MultimediaEngine as IMultimediaEngine,

  // Financial Engine Types
  FinancialEngineConfig,
  FinancialAnalytics,
  RevenueMetrics,
  RevenueSource,
  GrowthMetrics,
  CostBreakdown,
  CostCategory,
  ProfitabilityAnalysis,
  CourseProfitability,
  PricingAnalysis,
  PricingStrategy,
  DiscountRule,
  BundleOption,
  RegionPrice,
  CompetitorPricing,
  PricingExperiment,
  PricingRecommendation,
  SubscriptionMetrics,
  TierMetrics,
  FinancialForecasts,
  Forecast,
  ScenarioAnalysis,
  FinancialRecommendation,
  DateRange,
  FinancialEngine as IFinancialEngine,

  // Predictive Engine Types
  PredictiveEngineConfig,
  PredictiveStudentProfile,
  PredictiveLearningHistory,
  PredictivePerformanceMetrics,
  PredictiveBehaviorPatterns,
  DemographicData,
  OutcomePrediction,
  PredictiveRiskFactor,
  SuccessFactor,
  PredictiveAction,
  StudentCohort,
  RiskAnalysis,
  AtRiskStudent,
  Intervention,
  InterventionRecommendation,
  InterventionPlan,
  PlannedIntervention,
  InterventionTimeline,
  InterventionMilestone,
  VelocityOptimization,
  VelocityRecommendation,
  PredictiveLearningSchedule,
  DailyGoal,
  PredictiveLearningContext,
  PredictiveCourseContext,
  EnvironmentFactors,
  ProbabilityScore,
  PredictiveEngine as IPredictiveEngine,

  // Analytics Engine Types
  AnalyticsEngineConfig,
  UserSAMStats,
  AnalyticsLearningMetrics,
  AnalyticsContentInsights,
  AnalyticsBehaviorPatterns,
  AnalyticsPersonalizedInsights,
  AnalyticsTrends,
  ComprehensiveAnalytics,
  AnalyticsOptions,
  AnalyticsSessionData,
  AnalyticsEngine as IAnalyticsEngine,

  // Memory Engine Types
  MemoryEngineConfig,
  MemoryConversationContext,
  MemoryEntry,
  MemoryConversationSummary,
  MemoryPersonalizedContext,
  MemoryMessage,
  MemoryConversationHistory,
  MemoryInitOptions,
  MemoryHistoryOptions,
  MemorySAMMessage,
  MemorySAMConversation,
  MemorySAMLearningProfile,
  MemoryDatabaseAdapter,
  MemoryEngine as IMemoryEngine,

  // Research Engine Types
  ResearchEngineConfig,
  ResearchPaper,
  ResearchAuthor,
  ResearchPublication,
  ResearchFinding,
  ResearchDataset,
  ResearchCodeRepository,
  ResearchEducationalMetrics,
  ResearchApplication,
  ResearchReview,
  ResearchCategory,
  ResearchTrend,
  ResearchFundingInfo,
  ResearchLiteratureReview,
  ResearchTimeline,
  ResearchMetrics,
  ResearchCollaborationInfo,
  ResearchReadingList,
  ResearchQuery,
  ResearchDatabaseAdapter,
  ResearchEngine as IResearchEngine,

  // Trends Engine Types
  TrendsEngineConfig,
  TrendAnalysis,
  TrendSource,
  TrendCategory,
  TrendMarketSignal,
  TrendComparison,
  TrendPrediction,
  IndustryTrendReport,
  TrendFilter,
  TrendsDatabaseAdapter,
  TrendsEngine as ITrendsEngine,

  // Achievement Engine Types
  AchievementEngineConfig,
  Achievement,
  AchievementCategory,
  AchievementUnlockConditions,
  Challenge,
  ChallengeDifficulty,
  ChallengeCategory,
  ChallengeRequirements,
  ChallengeRequirementType,
  ChallengeRewards,
  AchievementProgress,
  AchievementTrackingResult,
  LevelUpInfo,
  AchievementSummary,
  AchievementContext,
  UserStats,
  AchievementDatabaseAdapter,
  AchievementEngine as IAchievementEngine,

  // Integrity Engine Types
  IntegrityEngineConfig,
  IntegrityCheckConfig,
  PlagiarismResult,
  SimilarityMatch,
  AIDetectionResult,
  AIAnalysisDetails,
  AIIndicator,
  ConsistencyResult,
  StyleMetrics,
  StyleAnomaly,
  IntegrityRiskLevel,
  IntegrityReport,
  IntegrityCheckOptions,
  CorpusEntry,
  IntegritySubmission,
  IntegrityDatabaseAdapter,
  IntegrityEngine as IIntegrityEngine,

  // Course Guide Engine Types
  CourseGuideEngineConfig,
  CourseGuideDepthMetrics,
  CourseGuideEngagementMetrics,
  CourseGuideMarketMetrics,
  CourseGuideMetrics,
  CourseGuideInsightItem,
  CourseGuideActionItem,
  TeacherInsights,
  SimilarCourse,
  CourseComparison,
  CourseGuideContentRecommendation,
  CourseGuideEngagementRecommendation,
  MarketingRecommendation,
  CourseSuccessPrediction,
  CourseGuideResponse,
  CourseGuideInput,
  CourseGuideChapter,
  CourseGuideSection,
  CourseGuideEnrollment,
  CourseGuideReview,
  CourseGuidePurchase,
  CourseGuideDatabaseAdapter,
  CourseGuideEngine as ICourseGuideEngine,

  // Collaboration Engine Types
  CollaborationEngineConfig,
  CollaborationActivityType,
  CollaborationContributionType,
  CollaborationReactionType,
  CollaborationReaction,
  CollaborationContribution,
  CollaborationParticipant,
  CollaborationActivity,
  CollaborationSessionMetrics,
  CollaborationTopic,
  CollaborationPattern,
  CollaborationInsights,
  CollaborationSession,
  CollaborationHotspot,
  CollaborationRealTimeMetrics,
  CollaborationSessionAnalytics,
  CollaborationParticipantMetric,
  CollaborationEngagementBucket,
  CollaborationRoleMetric,
  CollaborationTrendData,
  CollaborationParticipantAnalytics,
  CollaborationSharedResource,
  CollaborationContentAnalytics,
  CollaborationConnection,
  CollaborationNode,
  CollaborationCentralityScore,
  CollaborationCommunity,
  CollaborationNetworkAnalytics,
  CollaborationAnalytics,
  CollaborationDatabaseAdapter,
  CollaborationEngine as ICollaborationEngine,

  // Social Engine Types
  SocialEngineConfig,
  SocialGroupMember,
  SocialLearningGroup,
  SocialActivityMetrics,
  SocialCommunity,
  SocialInteraction,
  SocialEffectivenessFactor,
  SocialEffectivenessScore,
  SocialEngagementTrend,
  SocialEngagementMetrics,
  SocialLearningOutcome,
  SocialNetworkEffect,
  SocialSharingImpact,
  SocialMatchingFactor,
  SocialMentorshipActivity,
  SocialMatchingResult,
  SocialLeadershipAnalysis,
  SocialCommunicationPattern,
  SocialCommunicationAnalysis,
  SocialConflictAnalysis,
  SocialDynamicsRecommendation,
  SocialDynamicsAnalysis,
  SocialUser,
  SocialDatabaseAdapter,
  SocialEngine as ISocialEngine,

  // Innovation Engine Types
  InnovationEngineConfig,
  CognitiveFitness,
  CognitiveDimensionName,
  CognitiveDimension,
  FitnessExercise,
  FitnessProgress,
  FitnessMilestone,
  FitnessRecommendation,
  FitnessSession,
  LearningDNA,
  DNASequence,
  DNASegment,
  LearningTrait,
  LearningHeritage,
  AncestralPattern,
  EvolutionStage,
  InnovationAdaptation,
  DNAMutation,
  LearningPhenotype,
  InnovationCapability,
  InnovationLimitation,
  PotentialArea,
  StudyBuddy,
  BuddyPersonalityType,
  BuddyPersonality,
  PersonalityTrait,
  BuddyAvatar,
  BuddyRelationship,
  SharedExperience,
  BuddyCapability,
  BuddyInteractionType,
  BuddyInteraction,
  BuddyEffectiveness,
  BuddyAdjustment,
  BuddyPreferences,
  QuantumPath,
  PathSuperposition,
  QuantumState,
  QuantumLearningNode,
  QuantumProperties,
  PathEntanglement,
  EntanglementEffect,
  PathObservationType,
  PathObservation,
  ObservationImpact,
  PathCollapse,
  PathProbability,
  TimeDistribution,
  OutcomeDistribution,
  QuantumPotentialOutcome,
  UncertaintyMeasure,
  InnovationDatabaseAdapter,
  InnovationLearningData,
  InnovationEngine as IInnovationEngine,

  // Market Engine Types
  MarketEngineConfig,
  MarketAnalysisType,
  MarketAnalysisRequest,
  CompetitorAnalysis,
  MarketValueAssessment,
  MarketPricingAnalysis,
  CompetitionAnalysis,
  TargetAudienceDemographics,
  TargetAudience,
  BrandingAnalysis,
  MarketGrowthLevel,
  MarketTrendAnalysis,
  MarketRecommendations,
  MarketAnalysisResponse,
  MarketCourseData,
  StoredMarketAnalysis,
  MarketDatabaseAdapter,
  MarketEngine as IMarketEngine,

  // Unified Bloom's Engine Types (Priority 1: Unified Bloom's Engine)
  UnifiedBloomsConfig,
  UnifiedBloomsMode,
  UnifiedBloomsResult,
  UnifiedBloomsRecommendation,
  AnalysisOptions,
  AnalysisMetadata,
  UnifiedCourseInput,
  UnifiedCourseOptions,
  UnifiedCourseResult,
  ChapterAnalysis as UnifiedChapterAnalysis,
  CourseRecommendation as UnifiedCourseRecommendation,
  UnifiedLearningPath,
  PathwayStage,
  CognitiveProgressInput,
  CognitiveProgressResult,
  ProgressRecommendation,
  UnifiedSpacedRepetitionInput,
  UnifiedSpacedRepetitionResult,
  CacheEntry,
  CacheStats,
  UnifiedBloomsEngine as IUnifiedBloomsEngine,

  // Practice Problems Engine Types
  PracticeProblemType,
  ProblemDifficulty,
  HintType,
  PracticeProblemConfig,
  PracticeProblemInput,
  PracticeProblem,
  ProblemHint,
  ProblemOption,
  CodeTestCase,
  SolutionStep,
  ProblemAttempt,
  ProblemEvaluation,
  PracticeSessionStats,
  DifficultyRecommendation,
  SpacedRepetitionSchedule,
  PracticeProblemOutput,
  PracticeProblemDatabaseAdapter,
  PracticeProblemsEngine as IPracticeProblemsEngine,

  // Adaptive Content Engine Types
  AdaptiveLearningStyle,
  ContentFormat,
  ContentComplexity,
  ReadingPace,
  AdaptiveContentConfig,
  AdaptiveLearnerProfile,
  ContentToAdapt,
  AdaptationOptions,
  AdaptedChunk,
  EmbeddedKnowledgeCheck,
  SupplementaryResource,
  AdaptedContent,
  ContentInteractionData,
  StyleDetectionResult,
  AdaptiveContentDatabaseAdapter,
  AdaptiveContentEngine as IAdaptiveContentEngine,

  // Socratic Teaching Engine Types
  SocraticQuestionType,
  DialogueState,
  SocraticTeachingConfig,
  SocraticQuestion,
  SocraticStudentResponse,
  ResponseAnalysis,
  SocraticDialogue,
  DialogueExchange,
  DialoguePerformance,
  StartDialogueInput,
  SocraticResponse,
  ContinueDialogueInput,
  SocraticDatabaseAdapter,
  SocraticTeachingEngine as ISocraticTeachingEngine,

  // Knowledge Graph Engine Types
  KnowledgeGraphEngineConfig,
  Concept,
  ConceptType,
  ConceptRelation,
  RelationType,
  ConceptMastery,
  ConceptMasteryLevel,
  MasteryEvidence,
  KnowledgeGraph,
  GraphStats,
  ConceptExtractionInput,
  ConceptExtractionResult,
  ExtractedConcept,
  ExtractedRelation,
  PrerequisiteAnalysisInput,
  PrerequisiteAnalysisResult,
  PrerequisiteNode,
  PrerequisiteGapAnalysis,
  ConceptGap,
  GapSuggestion,
  LearningPathInput,
  LearningPath,
  LearningPathNode,
  PathActivity,
  LearningPathProgress,
  CourseKnowledgeAnalysisInput,
  CourseKnowledgeAnalysisResult,
  CourseStructureQuality,
  StructureIssue,
  KnowledgeGraphRecommendation,
  ConceptCoverage,

  // Microlearning Engine Types
  MicrolearningEngineConfig,
  MicroModuleType,
  MicrolearningContentFormat,
  DeviceType,
  DeliveryScheduleType,
  MicroModuleStatus,
  MicroModule,
  MicroModuleContent,
  ContentBlock,
  MediaAttachment,
  InteractionElement,
  MicroModuleMetrics,
  ChunkingInput,
  ChunkingResult,
  ContentChunk,
  ChunkingCoverage,
  DeliverySchedule,
  ScheduledModule,
  DeliveryPreferences,
  ModulePerformance,
  MicrolearningSession,
  SessionModule,
  SessionPerformance,
  MobileOptimizationInput,
  MobileOptimizedContent,
  MobileCard,
  LoadingChunk,
  SpacedRepetitionConfig,
  SpacedRepetitionUpdate,
  MicrolearningSRResult,
  MicrolearningAnalytics,
  OverallStats,
  StreakStats,
  LearningPatterns,
  ModuleBreakdown,
  MicrolearningRecommendation,
  GenerateModulesInput,
  GenerateModulesResult,
  ScheduleSuggestion,
  CreateSessionInput,
  UpdateProgressInput,
  GetAnalyticsInput,

  // Metacognition Engine Types
  MetacognitionEngineConfig,
  ReflectionDepth,
  ReflectionType,
  MetacognitiveSkill,
  LearningStrategy,
  StudyHabitCategory,
  ConfidenceLevel,
  CognitiveLoadLevel,
  ReflectionPrompt,
  ReflectionContext,
  ReflectionResponse,
  ReflectionAnalysis,
  ActionItem,
  StudySession as MetacognitionStudySession,
  StudyBreak,
  StudyEnvironment,
  SessionOutcome,
  StudyHabitAnalysis,
  TimeSlot,
  StrategyEffectiveness,
  FocusPattern,
  BreakPattern,
  StudyHabitRecommendation,
  StrategyProfile,
  StrategyUsage,
  StrategyRecommendation,
  KnowledgeConfidenceAssessment,
  ConfidenceItem,
  CognitiveLoadAssessment,
  CognitiveLoadFactor,
  LoadOptimizationRecommendation,
  LearningGoal,
  GoalType,
  GoalMilestone,
  GoalReflection,
  GoalMonitoringResult,
  GoalMetric,
  MetacognitiveSkillAssessment,
  MetacognitiveSkillScore,
  MetacognitiveExercise,
  SelfRegulationProfile,
  EmotionalRegulationMetrics,
  MotivationRegulationMetrics,
  AttentionRegulationMetrics,
  RegulationIntervention,
  GenerateReflectionInput,
  GenerateReflectionResult,
  AnalyzeReflectionInput,
  RecordStudySessionInput,
  GetHabitAnalysisInput,
  AssessConfidenceInput,
  SetGoalInput,
  UpdateGoalProgressInput,
  GetMetacognitiveAssessmentInput,
  RecommendStrategiesInput,
  RecommendStrategiesResult,
  AssessCognitiveLoadInput,
  ContentStrategyMatch,

  // Competency Engine Types
  CompetencyEngineConfig,
  CompetencyFramework,
  SkillCategory,
  ProficiencyLevel,
  SkillRelationType,
  CareerLevel,
  PortfolioItemType,
  CompetencySkill,
  FrameworkMapping,
  MarketDemand,
  SkillRelation,
  SkillTree,
  SkillTreeNode,
  SkillTreeEdge,
  DifficultyProgression,
  TierInfo,
  CompetencyLearningResource,
  UserSkillProficiency,
  ProficiencyEvidence,
  CompetencyProfile,
  SkillGap,
  SkillRecommendation,
  JobRole,
  RoleSkillRequirement,
  SalaryRange,
  GrowthOutlook,
  JobRoleMatch,
  PartialSkillMatch,
  CompetencyCareerPath,
  CareerStage,
  CareerBranch,
  SkillProgressionMap,
  SkillEvolution,
  CareerPathAnalysis,
  CareerPathRecommendation,
  CareerProjection,
  PortfolioItem,
  DemonstratedSkill,
  PortfolioArtifact,
  PortfolioVerification,
  ImpactMetrics,
  CompetencyPortfolio,
  PortfolioSummary,
  SkillCoverageAnalysis,
  PortfolioRecommendation,
  SkillAssessment,
  CompetencyAssessmentType,
  AssessmentItem,
  CompetencyAssessmentRubric,
  CompetencyRubricCriterion,
  ProficiencyScoreMapping,
  AssessmentResult,
  ItemResult,
  CreateSkillTreeInput,
  GetUserCompetencyInput,
  MatchJobRolesInput,
  MatchJobRolesResult,
  AnalyzeCareerPathInput,
  AddPortfolioItemInput,
  AssessSkillInput,
  UpdateProficiencyInput,
  ExtractSkillsInput,
  ExtractSkillsResult,
  ExtractedSkillInfo,
  GenerateSkillTreeInput,
  GetSkillGapAnalysisInput,
  SkillGapAnalysisResult,

  // Peer Learning Engine Types
  PeerLearningEngineConfig,
  MatchingAlgorithm,
  ReputationWeights,
  PeerProfile,
  PeerExpertise,
  PeerProficiencyLevel,
  Endorsement,
  PeerLearningGoal,
  PeerGoalPriority,
  PeerGoalStatus,
  PeerAvailability,
  WeeklySchedule,
  PeerTimeSlot,
  PeerDateRange,
  PeerPreferences,
  GroupSizePreference,
  CommunicationStyle,
  PeerLearningStyle,
  SessionFormat,
  AgeRange,
  PeerStats,
  PeerBadge,
  BadgeCategory,
  BadgeTier,
  ReputationScore,
  ReputationChange,
  ReputationCategory,
  PeerMatch,
  MatchReason,
  ComplementarySkill,
  CompatibilityFactor,
  PeerMatchCriteria,
  MatchType,
  StudyGroup,
  GroupType,
  GroupVisibility,
  GroupStatus,
  GroupMember,
  GroupRole,
  AttendanceRecord,
  GroupSchedule,
  ScheduleFrequency,
  GroupGoal,
  GroupMilestone,
  GroupResource,
  PeerResourceType,
  GroupSession,
  SessionStatus,
  GroupSessionType,
  SessionAttendee,
  AttendeeStatus,
  SessionAgenda,
  SessionRecording,
  SessionFollowUp,
  PeerActionItem,
  GroupStats,
  GroupSettings,
  NotificationPreferences,
  ModerationSettings,
  DiscussionThread,
  ThreadAuthor,
  ThreadType,
  ThreadStatus,
  DiscussionReply,
  EditRecord,
  Reaction,
  ReactionType,
  Mentorship,
  MentorshipStatus,
  MentorshipType,
  MentorProfile,
  MentoringStyle,
  Testimonial,
  MenteeProfile,
  CommitmentLevel,
  MentorshipGoal,
  MentorshipMilestone,
  MentoringSession,
  MentoringSessionType,
  SessionFeedback,
  MentorshipFeedback,
  FeedbackType,
  MentorshipAgreement,
  AgreementExpectation,
  PeerReviewAssignment,
  PeerReviewType,
  ReviewAssignmentStatus,
  ReviewSubmission,
  SubmissionAttachment,
  PeerReviewRubric,
  ReviewCriterion,
  CriterionLevel,
  PeerReview,
  CriterionScore,
  PeerConfidenceLevel,
  ReviewCalibration,
  CollaborativeProject,
  ProjectType,
  ProjectStatus,
  ProjectTeam,
  ProjectMember,
  MemberStatus,
  ProjectRoleDefinition,
  TeamSkillMatrix,
  MemberSkillEntry,
  ProjectMilestone,
  MilestoneStatus,
  MilestoneReview,
  ProjectTask,
  TaskStatus,
  TaskPriority,
  TaskComment,
  ProjectResource,
  ResourceVersion,
  RepositoryInfo,
  ProjectCommunication,
  CommunicationType,
  ProjectReview,
  ReviewerType,
  ProjectReviewCriterion,
  CreatePeerProfileInput,
  UpdatePeerProfileInput,
  FindPeerMatchesInput,
  CreateStudyGroupInput,
  JoinGroupInput,
  CreateGroupSessionInput,
  CreateDiscussionInput,
  CreateReplyInput,
  RequestMentorshipInput,
  CreatePeerReviewAssignmentInput,
  SubmitPeerReviewInput,
  CreateProjectInput,
  CreateProjectTaskInput,
  PeerMatchResult,
  GroupSearchResult,
  DiscussionSearchResult,
  MentorSearchResult,
  LeaderboardEntry,
  PeerLearningAnalytics,
  SubjectActivity,
  TrendDataPoint,
} from './types';

// ============================================================================
// VALIDATION EXPORTS (Canonical validation stack for SAM AI)
// ============================================================================

export {
  // Schemas
  BloomsLevelSchema,
  SubjectiveEvaluationResponseSchema,
  GradingAssistanceResponseSchema,
  RubricAlignmentSchema,
  ComparisonToExpectedSchema,
  AdaptiveQuestionResponseSchema,
  QuestionOptionSchema,
  AssessmentQuestionSchema,
  AssessmentQuestionsResponseSchema,
  BloomsDistributionSchema,
  ContentAnalysisResponseSchema,
  // JSON Extraction
  extractJson,
  extractJsonWithOptions,
  fixCommonJsonIssues,
  // Core Validation
  parseAndValidate,
  validateSchema,
  safeParseWithDefaults,
  // Retry Logic
  createRetryPrompt,
  executeWithRetry,
  DEFAULT_RETRY_CONFIG,
  // Advanced Validation
  createPartialSchema,
  validateWithDefaults,
  // Schema-Specific Validators
  validateEvaluationResponse,
  validateGradingAssistanceResponse,
  validateAdaptiveQuestionResponse,
  validateAssessmentQuestionsResponse,
  validateContentAnalysisResponse,
  // Types
  type BloomsLevel,
  type SubjectiveEvaluationResponse,
  type GradingAssistanceResponse,
  type AdaptiveQuestionResponse,
  type AssessmentQuestionsResponse,
  type ContentAnalysisResponse,
  type ValidationResult,
  type ValidationError,
  type JsonExtractionOptions,
  type JsonExtractionResult,
  type RetryConfig,
  type RetryOptions,
} from './validation';
