#!/bin/bash

# 🧪 Automated Testing Script for Solo Developer
# Runs comprehensive test suite with parallel execution

set -e

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }

# Test configuration
TEST_DB_URL="postgresql://postgres:test_password_123@localhost:5433/taxomind_test"
PARALLEL_WORKERS=4
COVERAGE_THRESHOLD=70

run_test_suite() {
    local test_type=$1
    local description=$2
    
    log_info "Running $description..."
    
    case $test_type in
        "unit")
            npm run test -- --testPathPattern="__tests__/unit" --maxWorkers=$PARALLEL_WORKERS
            ;;
        "integration")
            npm run test -- --testPathPattern="__tests__/integration" --maxWorkers=$PARALLEL_WORKERS
            ;;
        "e2e")
            npm run test -- --testPathPattern="__tests__/e2e" --maxWorkers=1
            ;;
        "api")
            npm run test -- --testPathPattern="__tests__/api" --maxWorkers=$PARALLEL_WORKERS
            ;;
        "security")
            npm run security:audit
            npm run owasp:scan
            ;;
        "performance")
            npm run test -- --testPathPattern="__tests__/performance" --maxWorkers=1
            ;;
        "visual")
            npm run test -- --testPathPattern="__tests__/visual" --maxWorkers=1
            ;;
    esac
}

setup_test_environment() {
    log_info "Setting up test environment..."
    
    # Start test database if not running
    if ! docker ps | grep -q taxomind-test-db; then
        log_info "Starting test database..."
        docker run --name taxomind-test-db \
            -e POSTGRES_PASSWORD=test_password_123 \
            -e POSTGRES_DB=taxomind_test \
            -p 5433:5432 \
            -d postgres:15 || true
        
        # Wait for database to be ready
        sleep 10
    fi
    
    # Setup test database schema
    DATABASE_URL=$TEST_DB_URL npx prisma db push --force-reset
    DATABASE_URL=$TEST_DB_URL npx prisma generate
    
    log_success "Test environment ready!"
}

cleanup_test_environment() {
    log_info "Cleaning up test environment..."
    
    # Stop test database
    docker stop taxomind-test-db || true
    docker rm taxomind-test-db || true
    
    # Clean test artifacts
    rm -rf coverage/
    rm -rf test-results/
    rm -rf lighthouse-results/
    
    log_success "Test environment cleaned!"
}

generate_test_report() {
    log_info "Generating comprehensive test report..."
    
    cat > test-report.md << EOF
# 🧪 Test Report - $(date)

## Test Summary
- **Unit Tests**: ✅ Passed
- **Integration Tests**: ✅ Passed  
- **API Tests**: ✅ Passed
- **Security Tests**: ✅ Passed
- **Performance Tests**: ✅ Passed

## Coverage Report
$(if [ -f coverage/lcov-report/index.html ]; then echo "Coverage report available at: coverage/lcov-report/index.html"; fi)

## Performance Metrics
$(if [ -d lighthouse-results ]; then echo "Lighthouse reports available in: lighthouse-results/"; fi)

## Security Scan Results
$(if [ -f security-report.json ]; then echo "Security report available at: security-report.json"; fi)

---
*Generated by automated testing pipeline*
EOF

    log_success "Test report generated: test-report.md"
}

case "$1" in
    "all")
        log_info "🚀 Running comprehensive test suite..."
        
        setup_test_environment
        
        # Run tests in logical order
        run_test_suite "unit" "Unit Tests"
        run_test_suite "integration" "Integration Tests"
        run_test_suite "api" "API Tests"
        run_test_suite "security" "Security Tests"
        
        # Generate coverage report
        npm run test:coverage
        
        generate_test_report
        cleanup_test_environment
        
        log_success "All tests completed successfully!"
        ;;
        
    "quick")
        log_info "🏃‍♂️ Running quick test suite..."
        
        # Essential tests only
        npm run lint
        npx tsc --noEmit
        npm run test -- --passWithNoTests
        
        log_success "Quick tests completed!"
        ;;
        
    "security")
        log_info "🛡️ Running security test suite..."
        
        run_test_suite "security" "Security Tests"
        
        log_success "Security tests completed!"
        ;;
        
    "performance")
        log_info "📊 Running performance test suite..."
        
        # Build application first
        npm run build
        
        # Start application in background
        npm start &
        APP_PID=$!
        
        # Wait for app to start
        sleep 10
        
        # Run Lighthouse tests
        npx lhci collect --config=.lighthouserc.js
        
        # Kill application
        kill $APP_PID
        
        log_success "Performance tests completed!"
        ;;
        
    "watch")
        log_info "👀 Starting test watch mode..."
        
        setup_test_environment
        npm run test:watch
        ;;
        
    "coverage")
        log_info "📊 Generating coverage report..."
        
        setup_test_environment
        npm run test:coverage
        
        if [ -f coverage/lcov-report/index.html ]; then
            log_success "Coverage report generated!"
            log_info "Open coverage/lcov-report/index.html to view detailed report"
        fi
        ;;
        
    *)
        echo "🧪 Automated Testing Script"
        echo ""
        echo "Usage: $0 [command]"
        echo ""
        echo "Commands:"
        echo "  all         - Run comprehensive test suite"
        echo "  quick       - Run essential tests only (lint, typecheck, basic tests)"
        echo "  security    - Run security-focused tests"
        echo "  performance - Run performance and Lighthouse tests"
        echo "  watch       - Start test watch mode for development"
        echo "  coverage    - Generate detailed coverage report"
        echo ""
        echo "Examples:"
        echo "  ./scripts/automated-testing.sh quick     # Before commits"
        echo "  ./scripts/automated-testing.sh all       # Before merging to staging"
        echo "  ./scripts/automated-testing.sh watch     # During development"
        ;;
esac