/**
 * SAM AI Assistant Library
 * Central export for all SAM utilities
 */

// Engine Presets
export {
  ENGINE_PRESETS,
  getEnginePreset,
  detectGenerationIntent,
  detectAnalysisIntent,
  selectEngines,
  type EnginePresetName,
} from './engine-presets';

// Form Actions
export {
  detectFormFields,
  generateFormSuggestions,
  generateFormActions,
  analyzeForm,
  executeFormFill,
  executeMultipleFormFills,
  clearFormFields,
  registerFormInteractions,
  getFormInteractions,
  type FormFieldInfo,
  type FormAction,
  type FormFillSuggestion,
  type FormAnalysis,
} from './form-actions';

// Gamification
export {
  GamificationEngine,
  createGamificationEngine,
  createGamificationHooks,
  XP_VALUES,
  LEVELS,
  ACHIEVEMENTS_CONFIG,
  type UserProgress,
  type Achievement,
  type Badge,
  type UserStats,
  type XPEvent,
  type XPEventType,
  type LevelInfo,
  type GamificationEvent,
} from './gamification';

// Entity Context - For context awareness
export {
  buildEntityContext,
  buildFormSummary,
  fetchCourseContext,
  fetchChapterContext,
  fetchSectionContext,
  type CourseContext,
  type ChapterContext,
  type SectionContext,
  type EntityContext,
  type PageFormData,
} from './entity-context';

// Quality Gates - Content validation pipeline (Priority 2)
export {
  // Pipeline
  ContentQualityGatePipeline,
  createQualityGatePipeline,
  validateContent,
  quickValidateContent,
  // Gates
  CompletenessGate,
  createCompletenessGate,
  ExampleQualityGate,
  createExampleQualityGate,
  DifficultyMatchGate,
  createDifficultyMatchGate,
  StructureGate,
  createStructureGate,
  DepthGate,
  createDepthGate,
  // Default configurations
  DEFAULT_PIPELINE_CONFIG,
  DEFAULT_COMPLETENESS_CONFIG,
  DEFAULT_EXAMPLE_QUALITY_CONFIG,
  DEFAULT_DIFFICULTY_MATCH_CONFIG,
  DEFAULT_STRUCTURE_CONFIG,
  DEFAULT_DEPTH_CONFIG,
  // Types
  type QualityGate,
  type GateResult,
  type GateIssue,
  type GeneratedContent,
  type ContentType,
  type DifficultyLevel,
  type ContentContext,
  type QualityGatePipelineConfig,
  type ValidationResult,
  type ValidationMetadata,
  type CompletenessGateConfig,
  type ExampleQualityGateConfig,
  type DifficultyMatchGateConfig,
  type StructureGateConfig,
  type DepthGateConfig,
} from './quality-gates';

// Schema Validation - Strict JSON validation (Priority 3)
export {
  // Bloom's Taxonomy
  BloomsLevelSchema,
  type BloomsLevel,
  // Question Types
  QuestionTypeSchema,
  type QuestionType,
  // Difficulty
  DifficultySchema,
  type Difficulty,
  // Subjective Evaluation
  SubjectiveEvaluationResponseSchema,
  type SubjectiveEvaluationResponse,
  // Grading Assistance
  RubricAlignmentSchema,
  type RubricAlignment,
  ComparisonToExpectedSchema,
  type ComparisonToExpected,
  GradingAssistanceResponseSchema,
  type GradingAssistanceResponse,
  // Adaptive Question
  QuestionOptionSchema,
  type QuestionOption,
  AdaptiveQuestionResponseSchema,
  type AdaptiveQuestionResponse,
  // Assessment Questions
  AssessmentQuestionSchema,
  type AssessmentQuestion,
  AssessmentQuestionsResponseSchema,
  type AssessmentQuestionsResponse,
  // Content Analysis
  ContentAnalysisResponseSchema,
  type ContentAnalysisResponse,
  // Validation Types
  type ValidationError,
  type ValidationAttemptResult,
  // Schema Registry
  EvaluationSchemas,
  type SchemaName,
  // JSON Extraction
  extractJson,
  type JsonExtractionOptions,
  type JsonExtractionResult,
  // Schema Validation
  validateSchema,
  parseAndValidate,
  // Retry Logic
  executeWithRetry,
  createRetryPrompt,
  DEFAULT_RETRY_CONFIG,
  type RetryConfig,
  // Schema-Specific Validators
  validateSubjectiveEvaluation,
  validateGradingAssistance,
  validateAdaptiveQuestion,
  validateAssessmentQuestions,
  validateContentAnalysis,
  // Partial/Lenient Validation
  createPartialSchema,
  validateWithDefaults,
  // Error Tracking
  type ErrorSeverity,
  type ErrorCategory,
  type TrackedError,
  type ErrorContext,
  type ErrorMetrics,
  type AlertConfig,
  type ErrorAlert,
  type TrackedValidationOptions,
  type ExecuteWithRetryFn,
  ValidationErrorTracker,
  getErrorTracker,
  createErrorTracker,
  DEFAULT_ALERT_CONFIG,
  createTrackedExecutor,
} from './schemas';

// Enhanced Orchestrator - Pipeline integration (Priority 4)
export {
  // Orchestrator
  EnhancedOrchestrator,
  createEnhancedOrchestrator,
  createSimpleOrchestrator,
  createStrictOrchestrator,
  // Types
  type BloomsDistribution,
  type BloomsAnalysis,
  type ValidatableContentType,
  type OrchestratedRequest,
  type OrchestratedResponse,
  type OrchestratedMetadata,
  type OrchestratedError,
  type BloomsAlignmentResult,
  type BloomsAdjustment,
  type PreGenerationHook,
  type PostGenerationHook,
  type PostValidationHook,
  type ValidationFailureHook,
  type BloomsAlignmentFailureHook,
  type ContentEnhancer,
  type BloomsAnalyzer,
  type EnhancedOrchestratorConfig,
  // Constants and utilities
  DEFAULT_ORCHESTRATOR_CONFIG,
  BLOOMS_LEVEL_ORDER,
  getBloomsLevelIndex,
  calculateBloomsDistance,
  isBloomsAligned,
} from './orchestrator';

// Pedagogical Evaluators - Educational effectiveness validation (Priority 5)
export {
  // Types
  type BloomsLevel as PedagogicalBloomsLevel,
  type BloomsDistribution as PedagogicalBloomsDistribution,
  type DifficultyLevel as PedagogicalDifficultyLevel,
  type StudentCognitiveProfile,
  type MasteryLevel,
  type LearningVelocity,
  type KnowledgeGap,
  type PerformanceMetrics,
  type PedagogicalContent,
  type PriorContentSummary,
  type PedagogicalEvaluationResult,
  type PedagogicalIssue,
  type PedagogicalEvaluator,
  type BloomsAlignerResult,
  type VerbAnalysis,
  type ActivityAnalysis,
  type ScaffoldingEvaluatorResult,
  type ComplexityProgression,
  type ComplexityJump,
  type PrerequisiteCoverage,
  type SupportStructure,
  type GradualReleaseAnalysis,
  type GradualReleasePhase,
  type ZPDEvaluatorResult,
  type ZPDZone,
  type ChallengeLevel,
  type ChallengeFactor,
  type SupportAdequacy,
  type EngagementPrediction,
  type PersonalizationFit,
  type PersonalizationOpportunity,
  type PedagogicalPipelineConfig,
  type PedagogicalPipelineResult,
  type BloomsAlignerConfig,
  type ScaffoldingEvaluatorConfig,
  type ZPDEvaluatorConfig,
  type PedagogicalPipelineFullConfig,
  // Constants
  BLOOMS_LEVEL_ORDER as PEDAGOGICAL_BLOOMS_LEVEL_ORDER,
  getBloomsLevelIndex as getPedagogicalBloomsLevelIndex,
  DIFFICULTY_LEVEL_ORDER,
  getDifficultyLevelIndex,
  DEFAULT_PEDAGOGICAL_PIPELINE_CONFIG,
  BLOOMS_VERBS,
  BLOOMS_ACTIVITIES,
  DEFAULT_BLOOMS_ALIGNER_CONFIG,
  SUPPORT_INDICATORS,
  GRADUAL_RELEASE_INDICATORS,
  COMPLEXITY_INDICATORS,
  DEFAULT_SCAFFOLDING_CONFIG,
  ZPD_ZONE_RANGES,
  ZONE_ENGAGEMENT_MAP,
  SUPPORT_TYPES,
  DEFAULT_ZPD_CONFIG,
  // Bloom's Aligner
  BloomsAligner,
  createBloomsAligner,
  createStrictBloomsAligner,
  createLenientBloomsAligner,
  // Scaffolding Evaluator
  ScaffoldingEvaluator,
  createScaffoldingEvaluator,
  createStrictScaffoldingEvaluator,
  createLenientScaffoldingEvaluator,
  // ZPD Evaluator
  ZPDEvaluator,
  createZPDEvaluator,
  createStrictZPDEvaluator,
  createLenientZPDEvaluator,
  // Pipeline
  PedagogicalPipeline,
  createPedagogicalPipeline,
  createBloomsPipeline,
  createScaffoldingPipeline,
  createZPDPipeline,
  createStrictPedagogicalPipeline,
  evaluatePedagogically,
} from './pedagogical';

// Calibration - Continuous improvement through human feedback (Priority 6)
export {
  // Types
  type CalibrationSample,
  type EvaluationContext,
  type VersionInfo,
  type HumanReview,
  type AdjustmentReason,
  type DriftAnalysis,
  type ContentTypeDrift,
  type AdjustmentReasonCount,
  type DriftRecommendation,
  type CalibrationResult,
  type CalibrationAdjustment,
  type CalibrationAlert,
  type CalibrationConfig,
  type AlertSettings,
  type CalibrationLoop,
  type EvaluationSampleInput,
  type DriftAnalysisOptions,
  type CalibrationStatus,
  type CalibrationSampleStore,
  type SampleStatistics,
  type PrismaSampleStoreConfig,
  type DriftAnalyzerConfig,
  type CalibratorConfig,
  type CalibrationLogger,
  // Constants
  DEFAULT_CALIBRATION_CONFIG,
  DEFAULT_DRIFT_ANALYZER_CONFIG,
  // Sample Store
  InMemorySampleStore,
  PrismaSampleStore,
  createInMemorySampleStore,
  createPrismaSampleStore,
  getDefaultSampleStore,
  resetDefaultSampleStore,
  // Drift Analyzer
  DriftAnalyzer,
  createDriftAnalyzer,
  createDriftAnalyzerFromCalibrationConfig,
  analyzeDrift,
  // Calibrator
  EvaluationCalibrator,
  createEvaluationCalibrator,
  createStrictCalibrator,
  createLenientCalibrator,
  getDefaultCalibrator,
  resetDefaultCalibrator,
} from './calibration';

// Memory Integration - Evaluation to student profile connection (Priority 7)
export {
  // Types
  type MasteryLevel as MemoryMasteryLevel,
  type TopicMastery,
  type MasteryUpdate,
  type PathwayStep,
  type LearningPathway,
  type PathwayAdjustment,
  type ReviewPriority,
  type ReviewScheduleEntry,
  type SpacedRepetitionConfig,
  type LearningStyle,
  type CognitivePreferences,
  type PerformanceMetrics as MemoryPerformanceMetrics,
  type StudentProfile,
  type EvaluationOutcome,
  type OutcomeRecordingResult,
  type MemoryEntryType,
  type ImportanceLevel,
  type MemoryEntry,
  type StudentProfileStore,
  type ReviewScheduleStore,
  type MemoryStore,
  type MemoryIntegrationConfig,
  type EvaluationMemoryIntegration,
  type MasteryTrackerConfig,
  type MasteryUpdateResult,
  type MasteryRecommendation,
  type MasterySummary,
  type PathwayCalculatorConfig,
  type PathwayAdjustmentResult,
  type RemediationTemplate,
  type SchedulingResult,
  type ReviewSessionResult,
  type ReviewStats,
  type EvaluationMemoryIntegrationImplConfig,
  type MemoryIntegrationLogger,
  type PrismaStudentProfileStoreConfig,
  // Constants
  DEFAULT_SPACED_REPETITION_CONFIG,
  DEFAULT_MEMORY_INTEGRATION_CONFIG,
  DEFAULT_MASTERY_TRACKER_CONFIG,
  DEFAULT_PATHWAY_CALCULATOR_CONFIG,
  // Student Profile Store
  InMemoryStudentProfileStore,
  PrismaStudentProfileStore,
  createInMemoryStudentProfileStore,
  createPrismaStudentProfileStore,
  getDefaultStudentProfileStore,
  resetDefaultStudentProfileStore,
  // Mastery Tracker
  MasteryTracker,
  createMasteryTracker,
  // Pathway Calculator
  PathwayCalculator,
  createPathwayCalculator,
  // Spaced Repetition
  SpacedRepetitionScheduler,
  InMemoryReviewScheduleStore,
  createSpacedRepetitionScheduler,
  createInMemoryReviewScheduleStore,
  getDefaultReviewScheduleStore,
  resetDefaultReviewScheduleStore,
  // Memory Integration
  EvaluationMemoryIntegrationImpl,
  InMemoryMemoryStore,
  createEvaluationMemoryIntegration,
  createInMemoryMemoryStore,
  getDefaultMemoryStore,
  resetDefaultMemoryStore,
} from './memory';

// Hardened Evaluation - Assessment reliability (Priority 8)
export {
  // Types
  type Rubric,
  type RubricCriterion,
  type RubricLevel,
  type StudentResponse,
  type ResponseAttachment,
  type ScoringSource,
  type ScoreResult,
  type CriterionScore,
  type AgreementLevel,
  type VerificationResult,
  type VerifiedEvaluation,
  type HumanReviewResult,
  type AdversarialVariation,
  type AdversarialType,
  type AdversarialTestResult,
  type AnswerKeyVerification,
  type AnswerKeyIssue,
  type HumanReviewRequest,
  type HumanReviewReason,
  type ReviewQueueStats,
  type HardenedEvaluatorConfig,
  type RulesBasedScorerConfig,
  type AdversarialGeneratorConfig,
  type RulesScoreBreakdown,
  type KeywordMatch,
  type LengthAnalysis,
  type StructureAnalysis,
  type CriterionMatch,
  type Penalty,
  type Bonus,
  type LLMScoreRequest,
  type LLMScoreResponse,
  type LLMScorer,
  type DualPassEvaluatorConfig,
  type DualPassLogger,
  type DualPassResult,
  type HumanReviewStore,
  type HumanReviewFlaggerConfig,
  type FlaggerLogger,
  type FlaggingResult,
  type FullHardenedEvaluatorConfig,
  type HardenedEvaluatorLogger,
  type HardenedEvaluationResult,
  type BatchEvaluationResult,
  // Constants
  DEFAULT_HARDENED_EVALUATOR_CONFIG,
  DEFAULT_RULES_BASED_SCORER_CONFIG,
  DEFAULT_ADVERSARIAL_GENERATOR_CONFIG,
  DEFAULT_FLAGGER_CONFIG,
  // Rules-Based Scorer
  RulesBasedScorer,
  createRulesBasedScorer,
  createScorerFromRubric,
  // Dual-Pass Evaluator
  DualPassEvaluator,
  MockLLMScorer,
  createDualPassEvaluator,
  createMockDualPassEvaluator,
  createRulesOnlyEvaluator,
  // Adversarial Generator
  AdversarialGenerator,
  createAdversarialGenerator,
  createComprehensiveGenerator,
  createQuickGenerator,
  // Human Review Flagger
  HumanReviewFlagger,
  InMemoryHumanReviewStore,
  createHumanReviewFlagger,
  createStrictFlagger,
  createLenientFlagger,
  getDefaultHumanReviewStore,
  resetDefaultHumanReviewStore,
  // Hardened Evaluator (Main Integration)
  HardenedEvaluator,
  createHardenedEvaluator,
  createStrictHardenedEvaluator,
  createLenientHardenedEvaluator,
  createRulesOnlyHardenedEvaluator,
} from './evaluation';

// Version Control - Prevent evaluation drift (Priority 9)
export {
  // Types
  type EvaluationConfig,
  type EvaluationParameters,
  type PromptTemplate,
  type PromptType,
  type GoldenTestCase,
  type TestCategory,
  type TestInput,
  type TestRubric,
  type ExpectedResult,
  type RegressionTestResult,
  type RegressionReport,
  type RegressionStatistics,
  type DriftAnalysisResult,
  type DriftDimension,
  type DriftTrend,
  type RootCause,
  type DriftRecommendation as VersionControlDriftRecommendation,
  type DriftAlert,
  type AlertType,
  type AlertConfiguration,
  type AlertChannel,
  // Default Configurations
  DEFAULT_EVALUATION_PARAMETERS,
  DEFAULT_DRIFT_THRESHOLDS,
  DEFAULT_ALERT_CONFIGURATION,
  // Version Controller
  EvaluationVersionController,
  InMemoryConfigStore,
  InMemoryPromptStore,
  createVersionController,
  createVersionControllerWithLogging,
  getDefaultVersionController,
  resetDefaultVersionController,
  type EvaluationConfigStore,
  type PromptTemplateStore,
  type VersionControllerConfig,
  type VersionControllerLogger,
  // Golden Test Repository
  GoldenTestRepository,
  GoldenTestCaseBuilder,
  InMemoryGoldenTestStore,
  createGoldenTestRepository,
  getDefaultGoldenTestRepository,
  resetDefaultGoldenTestRepository,
  createSampleRubric,
  createSampleTestCases,
  DEFAULT_REPOSITORY_CONFIG,
  type GoldenTestStore,
  type GoldenTestRepositoryConfig,
  type GoldenTestRepositoryLogger,
  type GoldenTestStatistics,
  type ImportResult,
  // Regression Runner
  RegressionRunner,
  MockEvaluationAdapter,
  createRegressionRunner,
  createMockRegressionRunner,
  DEFAULT_RUNNER_CONFIG,
  type EvaluationAdapter,
  type EvaluationResult as RegressionEvaluationResult,
  type RegressionRunnerConfig,
  type RegressionRunnerLogger,
  // Drift Alerting
  DriftAlerter,
  InMemoryAlertStore,
  LogChannelHandler,
  WebhookChannelHandler,
  createDriftAlerter,
  createDriftAlerterWithWebhook,
  getDefaultDriftAlerter,
  resetDefaultDriftAlerter,
  type DriftAlertStore,
  type AlertChannelHandler,
  type DriftAlerterConfig,
  type DriftAlerterLogger,
} from './version-control';

// Safety + Fairness - Bias and discouraging language detection (Priority 10)
export {
  // Types
  type SafetyResult,
  type SafetyIssue,
  type SafetyRecommendation,
  type SafetySeverity,
  type SafetyIssueType,
  type EvaluationFeedback,
  type DiscouragingLanguageResult,
  type DiscouragingMatch,
  type DiscouragingCategory,
  type BiasDetectionResult,
  type BiasIndicator,
  type BiasCategory,
  type AccessibilityResult,
  type AccessibilityIssue,
  type AccessibilityIssueType,
  type TextStatistics,
  type ConstructiveFramingResult,
  type FramingIssue,
  type FramingIssueType,
  type PositiveElement,
  type FairnessAuditReport,
  type FairnessAuditConfig,
  type DemographicAnalysis,
  type GroupStatistics,
  type FairnessRecommendation,
  type FairnessValidatorConfig,
  type SafetyLogger,
  // Default Configurations
  DEFAULT_FAIRNESS_CONFIG,
  SEVERITY_WEIGHTS,
  DEFAULT_ACCESSIBILITY_CONFIG,
  DEFAULT_CONSTRUCTIVE_CONFIG,
  DEFAULT_AUDIT_CONFIG,
  // Discouraging Language Detector
  DiscouragingLanguageDetector,
  createDiscouragingLanguageDetector,
  createStrictDiscouragingDetector,
  createLenientDiscouragingDetector,
  type DiscouragingLanguageDetectorConfig,
  // Bias Detector
  BiasDetector,
  createBiasDetector,
  createStrictBiasDetector,
  createLenientBiasDetector,
  createCategoryBiasDetector,
  type BiasDetectorConfig,
  // Accessibility Checker
  AccessibilityChecker,
  createAccessibilityChecker,
  createElementaryAccessibilityChecker,
  createHighSchoolAccessibilityChecker,
  createCollegeAccessibilityChecker,
  type AccessibilityCheckerConfig,
  // Constructive Framing Checker
  ConstructiveFramingChecker,
  createConstructiveFramingChecker,
  createStrictConstructiveChecker,
  createLenientConstructiveChecker,
  type ConstructiveFramingCheckerConfig,
  // Fairness Validator
  FairnessSafetyValidator,
  createFairnessSafetyValidator,
  createStrictFairnessValidator,
  createLenientFairnessValidator,
  createQuickFairnessValidator,
  getDefaultFairnessValidator,
  resetDefaultFairnessValidator,
  type FullFairnessValidatorConfig,
  // Fairness Auditor
  FairnessAuditor,
  createFairnessAuditor,
  createStrictFairnessAuditor,
  createLenientFairnessAuditor,
  ScheduledFairnessAuditRunner,
  type FullFairnessAuditorConfig,
  type EvaluationWithDemographics,
  // Convenience Functions
  validateFeedbackSafety,
  isFeedbackSafe,
  getFeedbackImprovements,
  rewriteFeedbackSafely,
  // Safe Evaluation Wrapper
  SafeEvaluationWrapper,
  createSafeEvaluationWrapper,
  createStrictSafeEvaluationWrapper,
  getDefaultSafeEvaluationWrapper,
  resetDefaultSafeEvaluationWrapper,
  wrapEvaluationWithSafety,
  isFeedbackTextSafe,
  getFeedbackSuggestions,
  type AIEvaluationResult,
  type SafeEvaluationResult,
  type SafeEvaluationWrapperConfig,
} from './safety';

// Unified Chat Integration - Main chat path with all subsystems (NEW)
export {
  UnifiedChatIntegration,
  createUnifiedChatIntegration,
  getUnifiedChatIntegration,
  resetUnifiedChatIntegration,
  type UnifiedChatConfig,
  type UnifiedChatResult,
  type PedagogyCheckResult,
  type MemoryUpdateResult,
  type UnifiedChatMetadata,
} from './unified-chat-integration';

// Real-Time Integration - WebSocket, Presence, Push Dispatcher (Phase 4)
export {
  // Client-side manager
  SAMRealtimeClient,
  createSAMRealtimeClient,
  getSAMRealtimeClient,
  // Server-side manager
  SAMRealtimeServer,
  createSAMRealtimeServer,
  getSAMRealtimeServer,
  // Singleton management
  resetSAMRealtimeInstances,
  // Integration with ProactiveScheduler
  pushProactiveIntervention,
  // Display configs
  DEFAULT_DISPLAY_CONFIGS,
  // Types
  type SAMRealtimeConfig,
} from './realtime';

// Telemetry Integration - Observability and Metrics (Phase 5)
export {
  // Service
  SAMTelemetryService,
  getSAMTelemetryService,
  createSAMTelemetryService,
  resetSAMTelemetryInstance,
  // Config
  DEFAULT_SAM_TELEMETRY_CONFIG,
  type SAMTelemetryConfig,
  // Status Enums
  ToolExecutionStatus,
  MemorySource,
  ResponseType as TelemetryResponseType,
  VerificationMethod,
  PlanEventType,
  ProactiveEventType,
  AlertSeverity,
  // Types
  type AgenticMetrics,
  type QuickMetricsSummary,
  type ToolMetrics,
  type MemoryQualityMetrics,
  type CalibrationMetrics,
  type PlanMetrics,
  type ProactiveMetrics,
  type SystemHealthMetrics,
  type Alert,
  type AlertRule,
  type ToolExecutionEvent,
  type MemoryRetrievalEvent,
  type ConfidencePrediction,
  type PlanLifecycleEvent,
  type ProactiveEvent,
} from './telemetry';
