"use client";

import { Smartphone, Shield, Download, QrCode } from 'lucide-react';

export const TOTPTutorial = () => {
  const authenticatorApps = [
    {
      name: 'Google Authenticator',
      platforms: ['iOS', 'Android'],
      links: {
        ios: 'https://apps.apple.com/app/google-authenticator/id388497605',
        android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2',
      },
    },
    {
      name: 'Microsoft Authenticator',
      platforms: ['iOS', 'Android'],
      links: {
        ios: 'https://apps.apple.com/app/microsoft-authenticator/id983156458',
        android: 'https://play.google.com/store/apps/details?id=com.azure.authenticator',
      },
    },
    {
      name: '1Password',
      platforms: ['iOS', 'Android', 'Desktop'],
      links: {
        website: 'https://1password.com',
      },
    },
    {
      name: 'Authy',
      platforms: ['iOS', 'Android', 'Desktop'],
      links: {
        website: 'https://authy.com',
      },
    },
  ];

  return (
    <div className="space-y-6">
      {/* What is TOTP Section */}
      <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-6">
        <div className="flex items-start gap-3">
          <Shield className="h-6 w-6 text-blue-600 dark:text-blue-400 mt-1" />
          <div>
            <h3 className="font-semibold text-blue-900 dark:text-blue-100 mb-2">
              What is Multi-Factor Authentication (MFA)?
            </h3>
            <p className="text-sm text-blue-700 dark:text-blue-300">
              MFA adds an extra layer of security by requiring a second verification code
              in addition to your password. This code is generated by an authenticator app
              on your smartphone and changes every 30 seconds.
            </p>
          </div>
        </div>
      </div>

      {/* How It Works */}
      <div>
        <h3 className="font-semibold mb-4 flex items-center gap-2">
          <QrCode className="h-5 w-5" />
          How It Works
        </h3>
        <div className="grid gap-4 md:grid-cols-3">
          <div className="bg-card border rounded-lg p-4">
            <div className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center mb-3 font-bold">
              1
            </div>
            <h4 className="font-medium mb-2">Download an App</h4>
            <p className="text-sm text-muted-foreground">
              Install an authenticator app on your smartphone from the list below
            </p>
          </div>
          <div className="bg-card border rounded-lg p-4">
            <div className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center mb-3 font-bold">
              2
            </div>
            <h4 className="font-medium mb-2">Scan QR Code</h4>
            <p className="text-sm text-muted-foreground">
              Use the app to scan the QR code displayed on the setup page
            </p>
          </div>
          <div className="bg-card border rounded-lg p-4">
            <div className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center mb-3 font-bold">
              3
            </div>
            <h4 className="font-medium mb-2">Enter Code</h4>
            <p className="text-sm text-muted-foreground">
              Enter the 6-digit code from your app to complete setup
            </p>
          </div>
        </div>
      </div>

      {/* Recommended Apps */}
      <div>
        <h3 className="font-semibold mb-4 flex items-center gap-2">
          <Download className="h-5 w-5" />
          Recommended Authenticator Apps
        </h3>
        <div className="grid gap-4 md:grid-cols-2">
          {authenticatorApps.map((app) => (
            <div key={app.name} className="bg-card border rounded-lg p-4 hover:shadow-md transition-shadow">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-muted rounded-lg flex items-center justify-center">
                  <Smartphone className="h-6 w-6 text-muted-foreground" />
                </div>
                <div className="flex-1">
                  <h4 className="font-medium mb-1">{app.name}</h4>
                  <p className="text-xs text-muted-foreground mb-2">
                    {app.platforms.join(', ')}
                  </p>
                  <div className="flex gap-2">
                    {app.links.ios && (
                      <a
                        href={app.links.ios}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline"
                      >
                        iOS
                      </a>
                    )}
                    {app.links.android && (
                      <a
                        href={app.links.android}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline"
                      >
                        Android
                      </a>
                    )}
                    {app.links.website && (
                      <a
                        href={app.links.website}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline"
                      >
                        Website
                      </a>
                    )}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Tips */}
      <div className="bg-amber-50 dark:bg-amber-950 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
        <h4 className="font-medium text-amber-900 dark:text-amber-100 mb-2">
          💡 Important Tips
        </h4>
        <ul className="text-sm text-amber-700 dark:text-amber-300 space-y-1 list-disc list-inside">
          <li>Save your recovery codes in a safe place (password manager recommended)</li>
          <li>You can use the same authenticator app for multiple accounts</li>
          <li>If you lose your phone, use recovery codes to regain access</li>
          <li>Contact support if you lose both your phone and recovery codes</li>
        </ul>
      </div>
    </div>
  );
};
