#!/usr/bin/env tsx
/**
 * Prisma Schema Merger
 *
 * Merges domain-specific schema files back into a single schema.prisma
 * for Prisma to consume. This enables modular schema management while
 * maintaining full Prisma compatibility.
 *
 * This script runs automatically before:
 * - npm run dev
 * - npm run build
 * - npx prisma generate
 * - npx prisma migrate
 */

import fs from 'fs';
import path from 'path';
import { glob } from 'glob';

interface MergeStats {
  filesProcessed: number;
  totalLines: number;
  timestamp: string;
  domains: string[];
}

async function mergeSchemaFiles(): Promise<MergeStats> {
  console.log('🔄 Merging Prisma schema files...\n');

  const domainsDir = path.join(process.cwd(), 'prisma', 'domains');
  const outputPath = path.join(process.cwd(), 'prisma', 'schema.prisma');

  // Check if domains directory exists
  if (!fs.existsSync(domainsDir)) {
    console.log('⚠️  Domains directory not found. Using existing schema.prisma');
    return {
      filesProcessed: 0,
      totalLines: 0,
      timestamp: new Date().toISOString(),
      domains: [],
    };
  }

  // Find all domain schema files (sorted by filename for consistent ordering)
  const schemaFiles = glob.sync('*.prisma', {
    cwd: domainsDir,
    absolute: true,
  }).sort();

  if (schemaFiles.length === 0) {
    console.log('⚠️  No domain schema files found');
    return {
      filesProcessed: 0,
      totalLines: 0,
      timestamp: new Date().toISOString(),
      domains: [],
    };
  }

  console.log(`📁 Found ${schemaFiles.length} domain schema files\n`);

  // Build the merged schema
  let mergedContent = `// ==========================================
// GENERATED SCHEMA - DO NOT EDIT MANUALLY
// ==========================================
//
// This file is automatically generated by merging domain-specific
// schema files from prisma/domains/
//
// To make changes:
// 1. Edit files in prisma/domains/
// 2. Run: npm run schema:merge
// 3. Run: npx prisma generate
//
// Generated: ${new Date().toISOString()}
// Source: ${schemaFiles.length} domain files
// ==========================================

`;

  const domains: string[] = [];
  let totalLines = 0;

  for (const file of schemaFiles) {
    const fileName = path.basename(file);
    const content = fs.readFileSync(file, 'utf-8');

    // Extract domain name from filename (e.g., "02-auth.prisma" -> "auth")
    const domainMatch = fileName.match(/\d+-(.+)\.prisma/);
    const domainName = domainMatch ? domainMatch[1] : fileName;
    domains.push(domainName);

    // Remove existing auto-generation warnings from individual files
    const cleanContent = content.replace(/\/\/ DO NOT EDIT MANUALLY.*\n/g, '');

    mergedContent += `\n// ==========================================\n`;
    mergedContent += `// Source: ${fileName}\n`;
    mergedContent += `// ==========================================\n\n`;
    mergedContent += cleanContent;

    const lineCount = content.split('\n').length;
    totalLines += lineCount;

    console.log(`✅ Merged ${fileName} (${lineCount} lines)`);
  }

  // Write the merged schema
  fs.writeFileSync(outputPath, mergedContent);

  console.log(`\n✅ Schema merged successfully!`);
  console.log(`   Output: ${outputPath}`);
  console.log(`   Total lines: ${totalLines}\n`);

  // Save merge stats
  const stats: MergeStats = {
    filesProcessed: schemaFiles.length,
    totalLines,
    timestamp: new Date().toISOString(),
    domains,
  };

  const statsPath = path.join(domainsDir, '.merge-stats.json');
  fs.writeFileSync(statsPath, JSON.stringify(stats, null, 2));

  return stats;
}

async function validateMergedSchema(): Promise<boolean> {
  console.log('🔍 Validating merged schema...\n');

  const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');

  if (!fs.existsSync(schemaPath)) {
    console.error('❌ Merged schema not found');
    return false;
  }

  const content = fs.readFileSync(schemaPath, 'utf-8');

  // Check for required sections
  const hasGenerator = /generator\s+\w+\s*{/.test(content);
  const hasDatasource = /datasource\s+\w+\s*{/.test(content);
  const hasModels = /model\s+\w+\s*{/.test(content);

  if (!hasGenerator) {
    console.error('❌ Validation failed: No generator found');
    return false;
  }

  if (!hasDatasource) {
    console.error('❌ Validation failed: No datasource found');
    return false;
  }

  if (!hasModels) {
    console.error('❌ Validation failed: No models found');
    return false;
  }

  // Count models
  const modelMatches = content.match(/model\s+\w+\s*{/g);
  const modelCount = modelMatches ? modelMatches.length : 0;

  console.log(`✅ Schema validation passed`);
  console.log(`   Generators: ${hasGenerator ? 'Found' : 'Missing'}`);
  console.log(`   Datasources: ${hasDatasource ? 'Found' : 'Missing'}`);
  console.log(`   Models: ${modelCount}\n`);

  return true;
}

async function main() {
  try {
    const stats = await mergeSchemaFiles();

    if (stats.filesProcessed === 0) {
      console.log('⚠️  No merge performed\n');
      process.exit(0);
    }

    const isValid = await validateMergedSchema();

    if (!isValid) {
      console.error('❌ Schema validation failed\n');
      process.exit(1);
    }

    console.log('📋 Next steps:');
    console.log('   1. Run: npx prisma generate');
    console.log('   2. Run: npx prisma migrate dev (if schema changed)');
    console.log('   3. Test your application\n');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error merging schema:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

export { mergeSchemaFiles, validateMergedSchema };
